### ISSUE TITLE
Player playtime via a discord command

### ISSUE THREAD

**Issue by IIPoliII** [joinandplaycoop/Bot#3]
We could add player playtime with ` !player IIPoliII` and it would return the hours played, maybe i can create a way to gather the stats only for that player from grafana.

**Comment by solarcloud7** [comment]
Since you know the schema better than I do,  would it be ok to ask you to give me a select statement with the data we are looking for?  that will expedite this feature! @IIPoliII 

I also think this is a great time to implement this feature

**Comment by solarcloud7** [comment]
http://dlpi02.poli.fun:3001/render/d-solo/iGZYzavZz/player-stats?orgId=1&from=1562577508071&to=1565169508071&var-Player=iipoliii&panelId=4&width=1000&height=500&tz=Europe%2FParis

http://dlpi02.poli.fun:3001/render/d-solo/iGZYzavZz/player-stats?orgId=1&from=1562577508071&to=1565169508071&var-Player=solarcloud7&panelId=4&width=1000&height=500&tz=Europe%2FParis

same with rockets.  these links show the vars to insert

**Comment by IIPoliII** [comment]
Yeah finnaly we will use the grafana then later maybe we will change it with MVC

**Comment by solarcloud7** [comment]
@IIPoliII Do those 2 links still work?  i'm having problems getting them to display a connection.

**Comment by IIPoliII** [comment]
Oh woops use perma link http://dlpi02.poli.fun:3000/render/d-solo/iGZYzavZz/player-stats?orgId=1&from=1562648433443&to=1565240433444&var-Player=JSONROY&panelId=4&width=1000&height=500&tz=Europe%2FZurich

**Comment by solarcloud7** [comment]
published live
