### ISSUE TITLE
Correct the discord cache issue

### ISSUE THREAD

**Issue by IIPoliII** [joinandplaycoop/Bot#4]
We need to add a timestamp like Y-m-d-H:M to avoid the discord cache.

**Comment by IIPoliII** [comment]
Surely bounded looks like the discord keep the rocket stats in their cache somehow https://media.discordapp.net/attachments/603832455744585728/608206189569769473/stat.png?width=400&height=200

**Comment by solarcloud7** [comment]
bug was in the config.json.   I did not update it and its not part of source control so has to be done by hand.

Also how we'er handling dynamic data is a little "hacky".   May have to come up with a better solution thats mor intuitive.

example: here is our file URL for rockets:
http://dlpi02.poli.fun:3000/render/d-solo/qS5B5IVWz/factorio-status?orgId=1&from=now{}%2Fd&to=now-0d%2Fd&fullscreen&panelId=10&tz=Europe%2FZurich

notice: &from=now{}%2Fd
the bot is formatting the string and inserting a variable in the url:

url = Config.cfg.imageUrls.rockets
days = str(-abs(daysAgo)) + "d" if daysAgo != 0 else ""
 url = url.format(days)

**Comment by solarcloud7** [comment]
fixed and is live
